const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, 'src', 'data', 'countries.json');
let data = JSON.parse(fs.readFileSync(file, 'utf8'));

const newFacts = {
  "AF": "The Bamiyan Buddhas stood for 1,500 years before being destroyed in 2001. They were taller than a 15 story building, carved directly into a cliff face.",
  "AL": "Albania's communist dictator was so paranoid about invasion that he built 173,000 bunkers, roughly one for every 11 people. Most have never been used.",
  "DZ": "Algeria is bigger than every country in Western Europe combined. The Sahara Desert alone covers 80% of its territory, an area larger than the entire Mediterranean Sea.",
  "AD": "Andorra has no airport, no railway, and no seaport. If you want to visit, you're driving through either France or Spain, there's literally no other way in.",
  "AO": "Angola is one of the world's top diamond producers, but it's also where the giant sable antelope lives, a creature so rare it was thought to be extinct until 2004.",
  "AG": "Antigua and Barbuda has exactly 365 beaches on the main island, one for every day of the year. Locals actually joke about which one is for leap years.",
  "AR": "Buenos Aires has more bookstores per capita than any city on Earth. Argentina also invented the ballpoint pen, a Hungarian designed it, but an Argentine manufactured it first.",
  "AM": "Armenia was the first nation to adopt Christianity as a state religion in 301 AD. They also produce some of the oldest wine in the world, with a 6,100 year old winery found in a cave.",
  "AU": "Australia is wider than the moon (by about 600 km). It's also the only continent country where you can drive for 14 hours and still be in the same state.",
  "AT": "Austria has produced more Nobel laureates per capita than almost any country. Mozart, Freud, Schrödinger, something in the Viennese coffee must help.",
  "AZ": "Azerbaijan is known as the Land of Fire because parts of the country literally burn continuously. Yanar Dag is a natural gas fire that has been blazing non stop for decades.",
  "BS": "The Bahamas has the clearest water in the world, visibility can reach over 200 feet. It's also home to the famous swimming pigs of Exuma.",
  "BH": "Bahrain is an island kingdom connected to Saudi Arabia by a 25 km bridge. It was the first place in the Middle East to discover oil in 1932.",
  "BD": "Cox's Bazar in Bangladesh is 150 km of unbroken sandy beach, the longest natural sea beach on the planet. You could walk it for three straight days and never run out of shoreline.",
  "BB": "Barbados is the birthplace of rum. They've been commercially producing it since 1703, making Mount Gay the oldest existing rum brand in the world.",
  "BY": "Belarus is home to the Belovezhskaya Pushcha, Europe's last primeval forest. It's the only place where European bison still roam completely free.",
  "BE": "Belgium produces over 220,000 tonnes of chocolate every year, but their real flex is having over 1,000 different varieties of beer.",
  "BZ": "Belize has the Great Blue Hole, a massive marine sinkhole that's visible from space. It's 300 meters across and incredibly deep, made famous by Jacques Cousteau.",
  "BJ": "Benin is the absolute birthplace of Voodoo (Vodun). It's an officially recognized religion there, celebrated with a massive festival every January.",
  "BT": "Bhutan doesn't measure GDP. Instead, they track 'Gross National Happiness' and they're serious about it. The government surveys every citizen on their wellbeing.",
  "BO": "Salar de Uyuni in Bolivia is so perfectly flat and reflective that when it rains, you literally can't tell where the sky ends and the ground begins. Satellites use it to calibrate their instruments.",
  "BA": "Sarajevo is one of the only cities in Europe where you can find a mosque, a Catholic church, an Orthodox church, and a synagogue all in the same neighborhood.",
  "BW": "Botswana is home to the Okavango Delta, a massive inland river system that doesn't flow into any ocean, it just evaporates into the Kalahari Desert.",
  "BR": "The Amazon produces 20% of the world's oxygen and is home to 10% of all species on Earth. One in ten known animals on the planet lives in Brazil's backyard.",
  "BN": "The Sultan of Brunei lives in the world's largest residential palace. It has 1,788 rooms, 257 bathrooms, and a banquet hall that seats 5,000 people.",
  "BG": "Bulgaria produces 85% of the world's rose oil. The Valley of Roses is so productive that Bulgarian oil is a key ingredient in almost every luxury perfume.",
  "BF": "Burkina Faso translates to 'Land of Honest Men'. It also hosts FESPACO, the largest African film festival, which transforms the capital every two years.",
  "BI": "Burundi has a traditional drumming culture so intense and unique that the Royal Drummers of Burundi are protected by UNESCO. The drums are carved from single tree trunks.",
  "CV": "Cabo Verde was completely uninhabited until Portuguese explorers found it in 1456. Now it's a massive cultural melting pot famous for its Morna music.",
  "KH": "Angkor Wat in Cambodia is the largest religious monument in the world. It was originally built as a Hindu temple before transforming into a Buddhist site.",
  "CM": "Cameroon is often called 'Africa in miniature' because it contains every single major climate and geographical zone found across the entire continent.",
  "CA": "Canada's coastline is 202,080 km long. If you walked it non stop, it would take you over 30 years. It also has more lakes than every other country combined.",
  "CF": "The Central African Republic is one of the best places in the world to see forest elephants and western lowland gorillas, thanks to the pristine Dzanga Sangha reserve.",
  "TD": "Lake Chad was once one of the largest freshwater lakes in the world, but it has shrunk by 95% since the 1960s, a dramatic shift visible from space.",
  "CL": "Chile is so absurdly long and thin that if you tipped it on its side from Africa, it would stretch from Lisbon to Moscow. Some parts are narrower than Manhattan is long.",
  "CN": "The Great Wall is longer than the distance from New York to Sydney. It took over 2,000 years to build, and contrary to the myth, you can't actually see it from space.",
  "CO": "Colombia produces 70 to 90% of the world's emeralds. The Spanish conquistadors went to absurd lengths to find their mines, the indigenous people kept them secret for generations.",
  "KM": "The Comoros islands are known as the 'Perfume Islands' because they are one of the world's leading producers of ylang ylang, the core scent in Chanel No. 5.",
  "CR": "Costa Rica dissolved its entire military in 1948 and put the budget into education and healthcare. It's one of the happiest countries on Earth.",
  "CI": "Cote d'Ivoire is the undisputed king of chocolate, producing nearly 40% of the world's cocoa beans. The country is literally the engine of the global chocolate industry.",
  "HR": "The necktie was invented in Croatia. During the 17th century, Croatian mercenaries wore distinctive knotted neckcloths, which the French quickly copied and called 'cravates'.",
  "CU": "Cuba has a 99.8% literacy rate, higher than the US, UK, and France. They also have more doctors per capita than almost any country on Earth.",
  "CY": "According to Greek mythology, Cyprus is the birthplace of Aphrodite, the goddess of love. The island is totally split between Greek and Turkish communities today.",
  "CZ": "The Czech Republic consumes more beer per capita than any other country in the world, and it's not even close. They invented the Pilsner style of beer in 1842.",
  "CD": "The Congo River is the deepest river in the world, plunging over 220 meters deep in some spots. It's so powerful it could theoretically power all of sub Saharan Africa.",
  "DK": "The Danish flag has been in continuous use since 1219, over 800 years. Legend says it literally fell from the sky during a battle, and they've never put it down since.",
  "DJ": "Djibouti contains Lake Assal, which is the lowest point in Africa and ten times saltier than the ocean. It's so hot and salty that massive salt formations cover the shores.",
  "DM": "Dominica is called the 'Nature Isle' and is home to the Boiling Lake, the second largest hot spring in the world. The water actually boils from volcanic heat.",
  "DO": "Santo Domingo in the Dominican Republic is the oldest continuously inhabited European settlement in the Americas, founded by Christopher Columbus's brother in 1496.",
  "EC": "Ecuador is named exactly after the equator. Because the Earth bulges at the middle, Mount Chimborazo in Ecuador is actually the closest point on Earth to space, not Everest.",
  "EG": "The Great Pyramid held the record for tallest human made structure for 3,800 years. Nothing surpassed it until Lincoln Cathedral in 1311. We still can't fully explain how it was built.",
  "SV": "El Salvador is the only country in Central America without a Caribbean coastline. It's totally Pacific, making it a legendary, albeit tiny, surfing destination.",
  "GQ": "Equatorial Guinea is the only country in Africa where Spanish is an official language. Despite being in Africa, its capital city is located on an island.",
  "ER": "Asmara, the capital of Eritrea, is known as the 'Miami of Africa'. It's packed with impeccably preserved Italian Art Deco architecture from the 1930s.",
  "EE": "Estonia is so digitally advanced that you can vote, pay taxes, and sign legal documents online. They even declared internet access a basic human right in 2000.",
  "SZ": "Eswatini (formerly Swaziland) is one of the last absolute monarchies in the world. The King hosts the massive Umhlanga reed dance every year with tens of thousands of participants.",
  "ET": "A goat herder named Kaldi noticed his goats dancing after eating certain berries. That's the origin story of coffee, and it happened in Ethiopia around the 9th century.",
  "FJ": "Fiji is made of exactly 333 islands. They also have a unique tradition called sevusevu, where visitors must present a bundle of kava root to the village chief upon arriving.",
  "FI": "Finland has 3.3 million saunas for 5.5 million people, that's roughly one sauna for every two Finns. Important business meetings happen in saunas.",
  "FR": "France gets more tourists per year than it has citizens, roughly 90 million visitors for a population of 67 million. Paris alone gets more visitors than any other city.",
  "GA": "Over 80% of Gabon is covered by pristine rainforest. They're doing such a good job conserving it that they are actually paid by the UN to keep their forests intact.",
  "GM": "The Gambia is the smallest country in mainland Africa, and it's basically just a sliver of land bordering the Gambia River, completely surrounded by Senegal.",
  "GE": "Georgia has been making wine for 8,000 years, making it the oldest wine producing region on Earth. They still make it the ancient way, buried underground in clay jars called qvevri.",
  "DE": "Germany has over 1,500 types of beer, but they also have over 3,000 varieties of bread. Germans take their bread so seriously that their bread culture is a UNESCO heritage.",
  "GH": "Ghana was the very first sub Saharan African nation to declare independence from European colonization in 1957. It paved the way for the rest of the continent.",
  "GR": "Greece has more archaeological museums than any other country, but here's what hits harder: democracy, the Olympics, Western philosophy, and theater were all invented in Athens.",
  "GD": "Grenada is known as the 'Spice Isle' because this tiny island produces over 20% of the world's nutmeg, a massive chunk of the global supply.",
  "GT": "Guatemala is the true birthplace of chocolate. The ancient Maya civilization were the first to roast cacao beans and create a bitter, spicy chocolate drink thousands of years ago.",
  "GN": "Guinea has a massive chunk of the world's bauxite reserves, the raw material used to make aluminum. Despite this wealth, much of the country remains incredibly wild.",
  "GW": "Guinea Bissau is composed of an archipelago of 88 islands where matriarchal societies still exist. On some islands, women hold all the economic and social power.",
  "GY": "Guyana is the only country in South America where English is the official language. A massive 80% of the country is untouched tropical rainforest.",
  "HT": "Haiti was the very first free black republic in the world. They successfully overthrew their colonizers in a massive slave revolt and declared independence in 1804.",
  "HN": "Honduras is home to Copan, an ancient Mayan city that has the most detailed and intricate stone carvings of any Mayan site in existence.",
  "HU": "The Rubik's Cube was invented by a Hungarian architect, Erno Rubik, in 1974. He originally built it just to help his students understand 3D geometry.",
  "IS": "Iceland is one of the very few inhabited places on Earth with zero mosquitoes. Scientists still aren't 100% sure why, but it involves their unique freeze thaw cycles.",
  "IN": "India's postal service delivers to over 1.5 billion people and has a floating post office on Dal Lake in Kashmir. It's the largest postal network on the planet.",
  "ID": "Indonesia is a massive archipelago of over 17,000 islands. It's home to the Komodo dragon, the heaviest lizard on Earth, which has venomous saliva.",
  "IR": "Iran, formerly Persia, is home to one of the world's oldest continuous major civilizations. They've been weaving the world's most intricate carpets for over 2,500 years.",
  "IQ": "Iraq is the cradle of civilization. Ancient Mesopotamia, located here, is where humanity invented writing (cuneiform), the wheel, and the 60 minute hour.",
  "IE": "Ireland's famous Guinness brewery in Dublin was leased by its founder in 1759 for 9,000 years at an annual rent of just 45 pounds. They're locked in for a while.",
  "IL": "Israel has the highest number of tech startups per capita in the world. The technology behind USB flash drives and Waze GPS was invented here.",
  "IT": "Italy has more UNESCO World Heritage sites than any other country in the world. They also have a free, 24 hour public wine fountain in the Abruzzo region.",
  "JM": "Jamaica produces some of the fastest runners in human history. It's also the birthplace of reggae, and James Bond was entirely created by Ian Fleming at his Jamaican estate.",
  "JP": "Kongō Gumi, founded in 578 AD, operated continuously for 1,400 years building Buddhist temples. Japan has thousands of businesses over 200 years old.",
  "JO": "Petra in Jordan is an entire ancient city carved directly into vibrant red sandstone cliff faces. It was lost to the Western world for centuries until discovered in 1812.",
  "KZ": "Kazakhstan is the world's largest landlocked country. It's so massive that it's larger than all of Western Europe combined, yet has a population smaller than New York State.",
  "KE": "Kenya is the world's original safari destination. It's also home to the Great Rift Valley, a massive geological trench that is literally splitting the African continent apart.",
  "KI": "Kiribati is the only country in the world situated in all four hemispheres (North, South, East, and West). Sadly, it's heavily threatened by rising sea levels.",
  "XK": "Kosovo is the youngest country in Europe, declaring independence in 2008. Over 70% of its population is under 35, making it the youngest population in Europe too.",
  "KW": "The Kuwaiti Dinar is the highest valued currency in the world. One Dinar is usually worth more than three US Dollars, thanks to massive oil reserves.",
  "KG": "Kyrgyzstan is almost entirely mountainous, often called the 'Switzerland of Central Asia'. It has one of the world's largest natural walnut forests.",
  "LA": "Laos is the most heavily bombed country per capita in history. Millions of unexploded bombs from the Vietnam War era still litter the countryside today.",
  "LV": "Latvia has an incredibly fast internet speed, often ranking in the top 10 globally. Over half the country is covered in thick, pristine forests.",
  "LB": "Lebanon is home to Byblos, one of the oldest continuously inhabited cities in the world, dating back over 7,000 years. The word 'Bible' actually comes from Byblos.",
  "LS": "Lesotho is entirely surrounded by South Africa and is the only country in the world that lies entirely above 1,000 meters in elevation. It's the 'Kingdom in the Sky'.",
  "LR": "Liberia was founded in the 1820s by freed American slaves. Its flag closely resembles the US flag, and its capital, Monrovia, is named after US President James Monroe.",
  "LY": "Libya is more than 90% desert. However, buried deep under the Sahara is the Nubian Sandstone Aquifer System, the world's largest known fossil water aquifer.",
  "LI": "Liechtenstein is so small it doesn't have an airport or a military. It's also the world's largest exporter of false teeth, producing over 60 million a year.",
  "LT": "Lithuania was the very last country in Europe to adopt Christianity. They held onto their pagan roots and nature worship until the late 14th century.",
  "LU": "Luxembourg is incredibly wealthy, boasting the highest GDP per capita in the world. In 2020, it became the first country to make all public transport entirely free.",
  "MG": "Because Madagascar has been isolated for millions of years, about 90% of its plants and animals, like all species of lemurs, are found literally nowhere else on Earth.",
  "MW": "Lake Malawi contains more species of fish than any other lake in the world, over 1,000 distinct species of vibrant cichlids that are popular in home aquariums.",
  "MY": "Malaysia's Petronas Twin Towers were the tallest buildings in the world until 2004. The country also has the world's largest underground cave chamber, the Sarawak Chamber.",
  "MV": "The Maldives is the lowest lying country on Earth, with an average ground level of just 1.5 meters above sea level. They held a famous underwater cabinet meeting to protest climate change.",
  "ML": "Timbuktu in Mali was once one of the wealthiest and most important centers of learning in the world. It was a legendary trading hub for gold, salt, and books.",
  "MT": "Malta has some of the oldest free standing stone structures in the world. The Megalithic Temples of Malta are older than Stonehenge and the Pyramids of Giza.",
  "MH": "The Marshall Islands were used by the US for 67 nuclear tests in the mid 20th century. Today, it's home to the largest shark sanctuary in the world.",
  "MR": "Mauritania is home to the 'Eye of the Sahara', a massive, deeply eroded geological dome that looks exactly like a giant bullseye from space.",
  "MU": "Mauritius was the only known habitat of the dodo bird, which went extinct in the 1600s. Today, it's one of Africa's most prosperous and democratic nations.",
  "MX": "Mexico City is built over a drained lake and is literally sinking at a rate of up to 20 inches per year. It's also the oldest capital city in the Americas.",
  "FM": "Micronesia is made up of 607 islands. It's home to Nan Madol, an ancient ruined city built on artificial islands connected by canals, often called the 'Venice of the Pacific'.",
  "MD": "Moldova has the largest wine cellar in the world. The Mileștii Mici cellar stretches for 200 kilometers underground and holds nearly 2 million bottles of wine.",
  "MC": "Monaco is smaller than New York's Central Park. It's so densely populated with millionaires that roughly one in three residents is classified as a millionaire.",
  "MN": "Mongolia is the most sparsely populated country in the world. It's a vast landscape where traditional nomadic culture, living in gers (yurts), is still very much alive.",
  "ME": "Montenegro literally translates to 'Black Mountain'. It features the Tara River Canyon, the deepest canyon in Europe, plunging over 1,300 meters deep.",
  "MA": "Morocco was the very first country to formally recognize the newly independent United States in 1777. The Moroccan American Treaty of Friendship is the US's oldest unbroken treaty.",
  "MZ": "Mozambique is the only national flag in the world that features a modern assault rifle. The AK 47 on the flag symbolizes defense and vigilance.",
  "MM": "Myanmar is home to Bagan, an ancient city that contains over 10,000 incredibly preserved Buddhist temples and pagodas stretching across a massive plain.",
  "NA": "Namibia has the oldest desert in the world, the Namib. It's also the first country in Africa to explicitly include environmental protection in its national constitution.",
  "NR": "Nauru is the smallest island nation in the world at just 21 square kilometers. It was once incredibly wealthy from phosphate mining, but the resources were totally depleted.",
  "NP": "Nepal is the only country whose flag isn't rectangular, it's two stacked triangles. The exact mathematical proportions are even defined directly in their constitution.",
  "NL": "About one third of the Netherlands lies entirely below sea level. They are masters of water management, holding back the ocean with massive networks of dikes and pumps.",
  "NZ": "New Zealand gave women the right to vote in 1893, a full 27 years before the US and 35 years before the UK. The petition that made it happen was the longest signed document in the country's history.",
  "NI": "Nicaragua has the only freshwater lake in the world containing oceanic animal life, including freshwater sharks, swordfish, and tarpon that adapted to the lake.",
  "NE": "Niger is home to some of the largest and most pristine dinosaur fossil beds in the world, buried deep within the sands of the Sahara desert.",
  "NG": "Nigeria's film industry, Nollywood, produces over 2,500 movies a year. That makes it the second largest film industry in the world by volume, ahead of Hollywood.",
  "KP": "North Korea uses its own calendar, the Juche calendar, which begins counting from the birth year of its founder, Kim Il sung (1912).",
  "MK": "Mother Teresa was born in Skopje, the capital of North Macedonia, in 1910. The country is also famous for its incredibly pristine Ohrid pearls.",
  "NO": "Raw salmon wasn't traditional Japanese sushi, Norway literally convinced Japan to try it in the 1980s as a marketing strategy. Now it's the most popular sushi globally.",
  "OM": "Oman is the oldest continuously independent state in the Arab world. It's famous for producing frankincense, resin extracted from desert trees, prized since antiquity.",
  "PK": "Pakistan has the second highest mountain on Earth, K2, and also contains the Khewra Salt Mine, the second largest salt mine in the world where pink Himalayan salt is harvested.",
  "PW": "Palau was the first country in the world to officially ban all shark fishing, creating a massive marine sanctuary the size of France to protect them.",
  "PA": "Panama is the only place in the world where you can see the sun rise on the Pacific Ocean and set on the Atlantic Ocean, due to the curve of the isthmus.",
  "PG": "Papua New Guinea is the most linguistically diverse country on Earth. With over 800 distinct languages spoken, it accounts for about 12% of the world's total languages.",
  "PY": "Paraguay's flag is completely unique: it's the only national flag in the world that has different emblems on the front and the back.",
  "PE": "Machu Picchu in Peru was built by the Inca in the 15th century but was completely unknown to the outside world until a local guide showed it to an American explorer in 1911.",
  "PH": "The Philippines is a massive archipelago made up of over 7,600 individual islands. It's also the undisputed text messaging capital of the world.",
  "PL": "Poland has the world's largest castle by land area, Malbork Castle, built entirely of brick by the Teutonic Knights in the 13th century.",
  "PT": "Portugal is the oldest nation state in Europe, keeping the exact same defined borders since the year 1139. It's also the world's largest producer of cork.",
  "QA": "Qatar is so arid that it has no natural rivers or lakes at all. Almost all of its fresh water is produced through massive, energy intensive desalination plants.",
  "CG": "Brazzaville in the Republic of the Congo and Kinshasa in the DRC are the closest two capital cities in the world, sitting right across the Congo River from each other.",
  "RO": "The Palace of the Parliament in Romania is the heaviest building on Earth, constructed from 1.5 billion pounds of steel and bronze, and massive amounts of marble.",
  "RU": "Russia is so unimaginably massive that it spans 11 different time zones. You could be eating breakfast in Moscow while someone in Vladivostok is having dinner.",
  "RW": "Rwanda has the highest percentage of women in parliament of any country in the world, holding over 60% of the seats. It's also famous for mountain gorilla conservation.",
  "KN": "Saint Kitts and Nevis is the smallest sovereign state in the Western Hemisphere, both in land area and population. It was the first English colony in the Caribbean.",
  "LC": "Saint Lucia is the only country in the world named entirely after a historical woman, Saint Lucy of Syracuse. It's famous for the Pitons, two massive volcanic spires.",
  "VC": "Saint Vincent and the Grenadines was a major filming location for the 'Pirates of the Caribbean' movies, thanks to its stunning and relatively untouched shorelines.",
  "WS": "Samoa completely skipped Friday, December 30, 2011. They jumped straight to Saturday to align their time zone with their main trading partners, Australia and New Zealand.",
  "SM": "San Marino is the oldest surviving republic in the world, founded by a stonemason in the year 301 AD. It's entirely surrounded by Italy.",
  "ST": "Sao Tome and Principe is the smallest African country. It's so perfectly positioned that it's the closest country on Earth to the intersection of the Equator and the Prime Meridian.",
  "SA": "Saudi Arabia is the largest country in the world entirely without a single permanent river. The country relies heavily on wadis (seasonal riverbeds) and desalination.",
  "SN": "Senegal is home to Lake Retba, which is naturally a vivid, bright pink color due to a specific type of salt loving algae that thrives in its hyper saline waters.",
  "RS": "Nikola Tesla, one of the greatest inventors in history, was an ethnic Serb. Today, the Serbian capital of Belgrade houses the Nikola Tesla Museum holding all his original patents.",
  "SC": "The Seychelles contains the Aldabra Atoll, home to over 150,000 giant tortoises. There are vastly more giant tortoises in the Seychelles than people.",
  "SL": "Sierra Leone's capital, Freetown, was literally founded as a home for freed slaves from London and the Americas in the late 18th century.",
  "SG": "Singapore is one of only three true city states left in the world (along with Monaco and Vatican City). It also boasts the world's tallest indoor waterfall.",
  "SK": "Slovakia has the highest number of castles and chateaux per capita in the world. There are over 100 castles and 400 manor houses scattered across the small country.",
  "SI": "Slovenia is incredibly green, over 60% of the country is covered in dense forest. It's also the only country in the world with the word 'LOVE' right in its name.",
  "SB": "The Solomon Islands are a hotspot for WWII history, with dozens of sunken warships and planes resting in the shallow, incredibly biodiverse coral reefs.",
  "SO": "Somalia has the longest coastline in mainland Africa. Due to its shape pointing into the Indian Ocean, it forms the tip of the region known as the Horn of Africa.",
  "ZA": "South Africa is the only country in the world to voluntarily completely dismantle its own nuclear weapons program. It also has three distinct capital cities.",
  "KR": "South Korea has the fastest average internet speeds in the world, and competitive video gaming (esports) is treated as a major, highly respected national sport.",
  "SS": "South Sudan is the absolute newest country on Earth. It officially gained its independence from Sudan in 2011 after decades of conflict.",
  "ES": "Spain has a festival called La Tomatina where tens of thousands of people gather just to throw over 100 metric tons of overripe tomatoes at each other in the streets.",
  "LK": "Sri Lanka was formally known as Ceylon, which is why Ceylon Tea is still the country's most famous export. It's shaped like a teardrop falling from India.",
  "SD": "Sudan actually has more ancient pyramids than Egypt. There are over 200 steep Nubian pyramids scattered across the desert, built by the ancient Kingdom of Kush.",
  "SR": "Suriname is the smallest country in South America, and one of the greenest on Earth. A staggering 93% of the country is covered in pristine Amazonian rainforest.",
  "SE": "Sweden is heavily forested, but it also has over 267,000 islands, making it the country with the most islands in the world. Only about 1,000 of them are inhabited.",
  "CH": "Switzerland hasn't been in a state of war since 1815. They take neutrality so seriously that their mountains are hollowed out with military bunkers and artillery.",
  "SY": "Damascus, the capital of Syria, is widely considered the oldest continuously inhabited city in the world, with evidence of civilization stretching back 11,000 years.",
  "TW": "Taiwan produces over 90% of the world's most advanced semiconductors. If you're using a modern smartphone or laptop, a chip from Taiwan is almost certainly powering it.",
  "TJ": "Tajikistan is known as the 'Roof of the World' because over 90% of its landmass is incredibly high, rugged mountains. It's a paradise for extreme alpinists.",
  "TZ": "Tanzania is home to Mount Kilimanjaro, the highest free standing mountain in the world, meaning it's not part of a mountain range, it just rises massively from the plains.",
  "TH": "Thailand is the only Southeast Asian country that was never colonized by a European power. The name literally translates to 'Land of the Free'.",
  "TL": "Timor Leste (East Timor) is one of the world's newest countries, gaining independence in 2002. It's one of only two predominantly Catholic countries in Asia.",
  "TG": "Togo is incredibly narrow, stretching just 115 km wide in some places, but stretching deep into Africa. It has a massive Voodoo market in its capital, Lome.",
  "TO": "Tonga is the only monarchy in the Pacific that was never completely colonized. It's also one of the few places on Earth you can swim with migrating humpback whales.",
  "TT": "Trinidad and Tobago is the absolute birthplace of the steel drum (steelpan), the only major acoustic instrument invented in the 20th century, made from oil barrels.",
  "TN": "Tunisia contains the ancient ruins of Carthage, the legendary city that once rivaled Rome. It's also heavily featured as the planet Tatooine in the Star Wars films.",
  "TR": "Istanbul, Turkey, is the only major city in the world that straddles two distinct continents, Europe and Asia, physically separated by the Bosphorus Strait.",
  "TM": "Turkmenistan is home to the 'Door to Hell', a massive natural gas crater that has been continuously burning in the middle of the Karakum Desert since 1971.",
  "TV": "Tuvalu is so small and remote that it earns a massive chunk of its national income just from leasing out its highly desirable internet domain extension: .tv.",
  "UG": "Uganda is incredibly biodiverse and is one of the only places on Earth where you can trek to see endangered mountain gorillas in their natural cloud forest habitat.",
  "UA": "Ukraine has the deepest metro station in the world, Arsenalna in Kyiv. It's so deep (105.5 meters) that taking the escalator down takes a full five minutes.",
  "AE": "The UAE transformed Dubai from a small desert port into a futuristic megacity in just 30 years. It's home to the Burj Khalifa, the tallest structure ever built by humans.",
  "GB": "The United Kingdom has arguably shaped the modern world more than any other nation, inventing the steam engine, the World Wide Web, and modern football.",
  "US": "The United States has no official language at the federal level. It also contains every single climate zone on Earth, from arctic tundra to tropical rainforest.",
  "UY": "Uruguay was the very first country in the world to completely legalize the recreational use of marijuana nationwide in 2013. It also runs on 98% renewable energy.",
  "UZ": "Uzbekistan is one of only two 'doubly landlocked' countries in the world, meaning to reach an ocean, you have to cross at least two other countries' borders.",
  "VU": "Bungee jumping originated in Vanuatu. Local men perform a ritual called land diving, leaping from massive wooden towers with only vines tied to their ankles.",
  "VA": "Vatican City is the world's smallest country at just 0.44 sq km, smaller than most city parks. Yet it has its own post office, radio station, and an ATM with Latin instructions.",
  "VE": "Venezuela is home to Angel Falls, the world's highest uninterrupted waterfall. The water drops a massive 979 meters, so far that much of it turns to mist before hitting the ground.",
  "VN": "Vietnam is the world's second largest exporter of coffee, right behind Brazil. They popularized robusta beans and serve it strong with sweetened condensed milk.",
  "YE": "Yemen is home to Shibam, an ancient city known as the 'Manhattan of the Desert'. It's packed with 500 year old mudbrick skyscrapers towering up to 11 stories high.",
  "ZM": "Zambia shares the magnificent Victoria Falls with Zimbabwe. It's also home to the massive Kasanka bat migration, where 10 million fruit bats darken the sky.",
  "ZW": "Zimbabwe has one of the world's highest literacy rates in Africa at over 90%. It also went through hyperinflation so extreme they printed a 100 Trillion dollar note."
};

data = data.filter(d => d.id !== 'PS');

data.forEach(d => {
  if (newFacts[d.id]) {
    d.fun_fact = newFacts[d.id];
  }
});

fs.writeFileSync(file, JSON.stringify(data, null, 0));
console.log('Facts updated and Palestine removed.');
